language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: HlFne5uCPrwnpqsoCAqBTmOg7r/JCbTvJm3gLUnfa8nlhX8iFJaGUxNcBdBAeQwrdZwXc8u1d2JBclvkuoxUj3dhTGOPsB06LQQrhHs+21VRxPb+m2ERBKCB/Q1s5AEnkGycJWT2+12T73G3xjP1yMeEUFMLMsm4Hd5ym/n5naY4ypQ+vaa84m96ReVGs+9upTWl4yRoK1euTiFt1wkNvhu7PYbwSwlKPloHcUdz1S/1MBRdc4K2cZ2smDyVE5VKJ/W8nbRb8dS990xaifBxofip8XQSZJMMwPDxcfAllMsTWEbLJDxPBcuuVGZr2pJxBeGIxn0BNhZIDwz4kFFC+XY1HIxS5xGnrnPLPSZbEliaTsdoUbYXwpYz9BiWzfrPJNGJuKNU/ZSiCAz6m5AzoarJLFaQ3rErFj9AhX6uIiR9tZRwxR5pCNQqTwezUfBiAQc3l8MPNZ6PL0m5F5Hd8J8xkX5nLNDM+EbL4ecqdIJgcwi5vCUouQINIo0qYOO1nutiDWhKcvaw2flUwnYwnOi53JLDP5lVETlRzd6cXt8pVKTRd700UgI+IJE2pRAKDZABIts4GZVa9kfW15L98a+savLAr8XD/8ZyYM2KmBJwWDKiCRS0bgsQ9gsX2raDXFet5I7a+hpVXAzSlckkHtCBSE5me5q//Oi1EwHn6Wc=
  app: node-blog
  on:
    repo: kaizen-minded/node-blog
